//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bissoft.CouncilCMS.Web.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CmsLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CmsLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bissoft.CouncilCMS.Web.Globalization.CmsLabels", typeof(CmsLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відсутні.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утримались.
        /// </summary>
        public static string Abstained {
            get {
                return ResourceManager.GetString("Abstained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прийнято.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актуальне.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додаткові питання.
        /// </summary>
        public static string AdditionalQuestions {
            get {
                return ResourceManager.GetString("AdditionalQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запорізька міська рада.
        /// </summary>
        public static string AdminCouncil {
            get {
                return ResourceManager.GetString("AdminCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проти.
        /// </summary>
        public static string Against {
            get {
                return ResourceManager.GetString("Against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усе на благо громади.
        /// </summary>
        public static string AllForPeople {
            get {
                return ResourceManager.GetString("AllForPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на головну сторінку.
        /// </summary>
        public static string BackToMain {
            get {
                return ResourceManager.GetString("BackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад в попередній розділ.
        /// </summary>
        public static string BackToSection {
            get {
                return ResourceManager.GetString("BackToSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонси подій.
        /// </summary>
        public static string Billboard {
            get {
                return ResourceManager.GetString("Billboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділи, що підпорядковуються.
        /// </summary>
        public static string ChildEnterprises {
            get {
                return ResourceManager.GetString("ChildEnterprises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зворотній зв&apos;язок.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пр. Соборний, 206&lt;br/&gt;м. Запоріжжя&lt;/br&gt;Україна&lt;br/&gt;69105	.
        /// </summary>
        public static string CouncilAddress {
            get {
                return ResourceManager.GetString("CouncilAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не прийнято.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість депутатів.
        /// </summary>
        public static string DeputyCount {
            get {
                return ResourceManager.GetString("DeputyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підрозділи.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук в розділі &quot;Документи&quot;.
        /// </summary>
        public static string DocFind {
            get {
                return ResourceManager.GetString("DocFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діапазон дати прийняття.
        /// </summary>
        public static string DocQueryDate {
            get {
                return ResourceManager.GetString("DocQueryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст в документі.
        /// </summary>
        public static string DocQueryText {
            get {
                return ResourceManager.GetString("DocQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва або номер документа.
        /// </summary>
        public static string DocQueryTitle {
            get {
                return ResourceManager.GetString("DocQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип документа.
        /// </summary>
        public static string DocQueryType {
            get {
                return ResourceManager.GetString("DocQueryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суб&apos;єкт подання.
        /// </summary>
        public static string DocSubject {
            get {
                return ResourceManager.GetString("DocSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копії документа для завантаження.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знайти документ.
        /// </summary>
        public static string FindDoc {
            get {
                return ResourceManager.GetString("FindDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фракція.
        /// </summary>
        public static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to від.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути всі.
        /// </summary>
        public static string GoToAll {
            get {
                return ResourceManager.GetString("GoToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гаряча лінія.
        /// </summary>
        public static string HotLine {
            get {
                return ResourceManager.GetString("HotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Олексія Савченко.
        /// </summary>
        public static string HotLineName {
            get {
                return ResourceManager.GetString("HotLineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        public static string LastNews {
            get {
                return ResourceManager.GetString("LastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі матеріали сайту доступні за ліцензією: Creative Commons Attribution 4.0 International.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Міський голова.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст повідомлення.
        /// </summary>
        public static string MsgText {
            get {
                return ResourceManager.GetString("MsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи відсутні.
        /// </summary>
        public static string NoEntry {
            get {
                return ResourceManager.GetString("NoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не голосували.
        /// </summary>
        public static string NotVote {
            get {
                return ResourceManager.GetString("NotVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офіційні сторінки в соцмережах.
        /// </summary>
        public static string OfficialSocila {
            get {
                return ResourceManager.GetString("OfficialSocila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Офіційний сайт.
        /// </summary>
        public static string OficialWebSite {
            get {
                return ResourceManager.GetString("OficialWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти на стару версію офіційного порталу.
        /// </summary>
        public static string OldSite {
            get {
                return ResourceManager.GetString("OldSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронне звернення.
        /// </summary>
        public static string OrganizationReception {
            get {
                return ResourceManager.GetString("OrganizationReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при виконанні запита.
        /// </summary>
        public static string PageError {
            get {
                return ResourceManager.GetString("PageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка в стадії наповнення.
        /// </summary>
        public static string PageInProcess {
            get {
                return ResourceManager.GetString("PageInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінку не знайдено.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотогалереї.
        /// </summary>
        public static string Photoreports {
            get {
                return ResourceManager.GetString("Photoreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посада.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата оприлюднення.
        /// </summary>
        public static string PostDate {
            get {
                return ResourceManager.GetString("PostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надрукувати.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професійна діяльність.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубліковано.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запис на прийом.
        /// </summary>
        public static string ReceptionForm {
            get {
                return ResourceManager.GetString("ReceptionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графік прийому.
        /// </summary>
        public static string ReceptionShedule {
            get {
                return ResourceManager.GetString("ReceptionShedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звертаємо увагу, що зазначена форма зв&apos;язку не є зверненням в розумінні Закону України &quot;Про зверненн громадян&quot;, а лише призначена для більш мобільного зв&apos;язку з органом місцевого самоврядування.
        /// </summary>
        public static string RequestTip {
            get {
                return ResourceManager.GetString("RequestTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рішення.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправити.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронні сервіси.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок денний.
        /// </summary>
        public static string SessionAgenda {
            get {
                return ResourceManager.GetString("SessionAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розпорядження про скликання сесії.
        /// </summary>
        public static string SessionDecree {
            get {
                return ResourceManager.GetString("SessionDecree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтр сесій міської ради.
        /// </summary>
        public static string SessionFilter {
            get {
                return ResourceManager.GetString("SessionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відео- та аудіозаписи сесії.
        /// </summary>
        public static string SessionMedia {
            get {
                return ResourceManager.GetString("SessionMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекти рішень міської ради.
        /// </summary>
        public static string SessionProjects {
            get {
                return ResourceManager.GetString("SessionProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протокол засідання сесії.
        /// </summary>
        public static string SessionProtocol {
            get {
                return ResourceManager.GetString("SessionProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регламент роботи сесії.
        /// </summary>
        public static string SessionReglament {
            get {
                return ResourceManager.GetString("SessionReglament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рішення міської ради.
        /// </summary>
        public static string SessionResolutions {
            get {
                return ResourceManager.GetString("SessionResolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про голосування.
        /// </summary>
        public static string SessionVotes {
            get {
                return ResourceManager.GetString("SessionVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Графік роботи.
        /// </summary>
        public static string Shedule {
            get {
                return ResourceManager.GetString("Shedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук на сайті.
        /// </summary>
        public static string SiteSearch {
            get {
                return ResourceManager.GetString("SiteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт працює в тестовому режимі.
        /// </summary>
        public static string TestLabel {
            get {
                return ResourceManager.GetString("TestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По батькові.
        /// </summary>
        public static string ThirdName {
            get {
                return ResourceManager.GetString("ThirdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенесено.
        /// </summary>
        public static string Transfered {
            get {
                return ResourceManager.GetString("Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оновлено.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відеорепортажі.
        /// </summary>
        public static string Videoreports {
            get {
                return ResourceManager.GetString("Videoreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосування.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода в Запоріжжі.
        /// </summary>
        public static string WeatherTitle {
            get {
                return ResourceManager.GetString("WeatherTitle", resourceCulture);
            }
        }
    }
}
