//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bissoft.CouncilCMS.Core.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bissoft.CouncilCMS.Core.Globalization.Locals", typeof(Locals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примінити.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прийнято.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акордеон.
        /// </summary>
        public static string Accordion {
            get {
                return ResourceManager.GetString("Accordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активно.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активні.
        /// </summary>
        public static string Actives {
            get {
                return ResourceManager.GetString("Actives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всі мови.
        /// </summary>
        public static string AllLanguages {
            get {
                return ResourceManager.GetString("AllLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Матеріал.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія матеріалів.
        /// </summary>
        public static string ArticleCategory {
            get {
                return ResourceManager.GetString("ArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підложка.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокувати.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблоковано.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблоковані.
        /// </summary>
        public static string Blockeds {
            get {
                return ResourceManager.GetString("Blockeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обидві.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текствоий блок.
        /// </summary>
        public static string Ckeditor {
            get {
                return ResourceManager.GetString("Ckeditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрити.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Панель керування.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессії міськради.
        /// </summary>
        public static string CouncilSession {
            get {
                return ResourceManager.GetString("CouncilSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити аккаунт.
        /// </summary>
        public static string CreateAcount {
            get {
                return ResourceManager.GetString("CreateAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поточна сесія міськради.
        /// </summary>
        public static string CurrentSession {
            get {
                return ResourceManager.GetString("CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошкоджені будівлі.
        /// </summary>
        public static string DamagedHousing {
            get {
                return ResourceManager.GetString("DamagedHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії будівель.
        /// </summary>
        public static string DamagedHousingCategory {
            get {
                return ResourceManager.GetString("DamagedHousingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані успішно збережені.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата створення.
        /// </summary>
        public static string DateCreate {
            get {
                return ResourceManager.GetString("DateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата останнього редагування.
        /// </summary>
        public static string DateLastEdit {
            get {
                return ResourceManager.GetString("DateLastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата прийняття.
        /// </summary>
        public static string DatePublish {
            get {
                return ResourceManager.GetString("DatePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не прийнято.
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За замовчуванням.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалено.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія документів.
        /// </summary>
        public static string DocumentCategory {
            get {
                return ResourceManager.GetString("DocumentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст документу.
        /// </summary>
        public static string DocumentText {
            get {
                return ResourceManager.GetString("DocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організація.
        /// </summary>
        public static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія організацій.
        /// </summary>
        public static string EnterpriseCategory {
            get {
                return ResourceManager.GetString("EnterpriseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жіноча.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string File1 {
            get {
                return ResourceManager.GetString("File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файли.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знайти.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Від.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерея зображеннь.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML код.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Іконка.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мова.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розташування.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логотип.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чоловіча.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобільний телефон.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані відсутні.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без посилання.
        /// </summary>
        public static string NoLink {
            get {
                return ResourceManager.GetString("NoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без назви.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чернетки.
        /// </summary>
        public static string NotPublished {
            get {
                return ResourceManager.GetString("NotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обрано.
        /// </summary>
        public static string NotSelect {
            get {
                return ResourceManager.GetString("NotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організація.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Організації.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статична сторінка.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва сторінки.
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка не знйдена.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PerLanguage {
            get {
                return ResourceManager.GetString("PerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персона.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорія персон.
        /// </summary>
        public static string PersonCategory {
            get {
                return ResourceManager.GetString("PersonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередні сесії міськради.
        /// </summary>
        public static string PreviouseSession {
            get {
                return ResourceManager.GetString("PreviouseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубліковані.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опубліковано.
        /// </summary>
        public static string Published1 {
            get {
                return ResourceManager.GetString("Published1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструватись.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скинути.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ролі.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збережено.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коротка назва.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показати всі.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підзаголовок.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблиця.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підказка.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перенесено.
        /// </summary>
        public static string Transfered {
            get {
                return ResourceManager.GetString("Transfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зовнішнє посилання.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувачі.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть, що ви ознайомились з необхідними документами.
        /// </summary>
        public static string valAllowRules {
            get {
                return ResourceManager.GetString("valAllowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач заблдокований, зверніться до адміністратора.
        /// </summary>
        public static string valBlocked {
            get {
                return ResourceManager.GetString("valBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля не співпадають.
        /// </summary>
        public static string valCompare {
            get {
                return ResourceManager.GetString("valCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат дати.
        /// </summary>
        public static string valDate {
            get {
                return ResourceManager.GetString("valDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат email.
        /// </summary>
        public static string valEmail {
            get {
                return ResourceManager.GetString("valEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідома помилка.
        /// </summary>
        public static string valException {
            get {
                return ResourceManager.GetString("valException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле повинно буди від {2} до {1} символів.
        /// </summary>
        public static string valLengthRange {
            get {
                return ResourceManager.GetString("valLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле повинно бути не більше {1} символів.
        /// </summary>
        public static string valMaxLength {
            get {
                return ResourceManager.GetString("valMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле повинно бути не менше {1} символів(а).
        /// </summary>
        public static string valMinLength {
            get {
                return ResourceManager.GetString("valMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скористайтесь пошуком вище та оберіть заявника або зареєструйте нового .
        /// </summary>
        public static string valNotSelectClient {
            get {
                return ResourceManager.GetString("valNotSelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат числа.
        /// </summary>
        public static string valNumber {
            get {
                return ResourceManager.GetString("valNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обов&apos;язкове поле.
        /// </summary>
        public static string valRequired {
            get {
                return ResourceManager.GetString("valRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть заявника або створіть нового.
        /// </summary>
        public static string valRequiredClient {
            get {
                return ResourceManager.GetString("valRequiredClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пертягніть мітку.
        /// </summary>
        public static string valRequiredLocation {
            get {
                return ResourceManager.GetString("valRequiredLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клієнт з таким email вже існує.
        /// </summary>
        public static string valSameEmail {
            get {
                return ResourceManager.GetString("valSameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач з таким логіном вже існує.
        /// </summary>
        public static string valSameLogin {
            get {
                return ResourceManager.GetString("valSameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть причину звернення.
        /// </summary>
        public static string valSelCause {
            get {
                return ResourceManager.GetString("valSelCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибиріть вулицю із списка .
        /// </summary>
        public static string valSelectStreet {
            get {
                return ResourceManager.GetString("valSelectStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть проблему.
        /// </summary>
        public static string valSelProblem {
            get {
                return ResourceManager.GetString("valSelProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть адресу проблеми.
        /// </summary>
        public static string valSetAddress {
            get {
                return ResourceManager.GetString("valSetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть номер будинка.
        /// </summary>
        public static string valSetHouse {
            get {
                return ResourceManager.GetString("valSetHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть вулицю.
        /// </summary>
        public static string valSetStreet {
            get {
                return ResourceManager.GetString("valSetStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обов&apos;язкове поле.
        /// </summary>
        public static string valSimpleRequired {
            get {
                return ResourceManager.GetString("valSimpleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний формат часу.
        /// </summary>
        public static string valTime {
            get {
                return ResourceManager.GetString("valTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неприпустимі символи (можна використовувати лише літери,цифри та знаки \ і /).
        /// </summary>
        public static string valWrongAddressSymbols {
            get {
                return ResourceManager.GetString("valWrongAddressSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цифри не співпадають.
        /// </summary>
        public static string valWrongCaptcha {
            get {
                return ResourceManager.GetString("valWrongCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувача з таким логіном не знайдено.
        /// </summary>
        public static string valWrongLogin {
            get {
                return ResourceManager.GetString("valWrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль вказано не вірно.
        /// </summary>
        public static string valWrongPassword {
            get {
                return ResourceManager.GetString("valWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вулицю не знайдено, перевірте назву вулиці або зітріть її та просто перетягніть мітку на карті.
        /// </summary>
        public static string valWrongStreet {
            get {
                return ResourceManager.GetString("valWrongStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версія.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMBED Відео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Віджет.
        /// </summary>
        public static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }
    }
}
