// <auto-generated />
namespace Bissoft.CouncilCMS.DAL.Migrations.Cms
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddWeatherWidgetHtmlField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWeatherWidgetHtmlField));
        
        string IMigrationMetadata.Id
        {
            get { return "201809051304147_AddWeatherWidgetHtmlField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
